/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bd_project;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.xml.bind.annotation.XmlElement;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.swing.JRViewer;
import oracle.jdbc.pool.OracleDataSource;

/**
 *
 * @author data base
 */
public class accountat2 extends javax.swing.JFrame {

    /**
     * Creates new form sealman2
     */
    public accountat2() {
        initComponents();
        jPanel1.addMouseListener(new MouseAdapter() {
                public void mousePressed(MouseEvent e) {
                   jListcustomer.clearSelection();
                   jListproduct.clearSelection();
                   jListsalesman.clearSelection();
                  
                }           
            });
    }
     Accountat aa;
   
   public void setuser(Accountat a){
       aa=a;
              // System.out.println("                                 \n"+aa.getSmId() );

       
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListproduct = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListsalesman = new javax.swing.JList<>();
        jButton8 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListcustomer = new javax.swing.JList<>();
        jtext_name = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton5 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(153, 102, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jListproduct.setBackground(new java.awt.Color(204, 204, 255));
        jListproduct.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(jListproduct);

        jListsalesman.setBackground(new java.awt.Color(204, 204, 255));
        jListsalesman.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jListsalesman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListsalesmanMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jListsalesman);

        jButton8.setText("edit mu information");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton10.setText("Edit ");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jLabel1.setText("ID");

        jLabel2.setText("name");

        jLabel3.setText("store type");

        jLabel4.setText("ID");

        jLabel5.setText("name");

        jLabel6.setText("price");

        jButton1.setText("search in ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("show all ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jListcustomer.setBackground(new java.awt.Color(204, 204, 255));
        jListcustomer.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jListcustomer);

        jtext_name.setText("name");
        jtext_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtext_nameActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "customer", "product", "salesman" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton5.setText("genareat report");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel7.setText("availability");

        jButton7.setText("delete");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel8.setText("place");

        jButton2.setText("add new salesman");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setText("Log Out");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel9.setText("ID");

        jLabel10.setText("name");

        jLabel11.setText("address");

        jLabel12.setText("salary");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel13.setText("product");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel14.setText("customer ");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel15.setText("salesman");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel9)
                        .addGap(57, 57, 57)
                        .addComponent(jLabel10)
                        .addGap(50, 50, 50)
                        .addComponent(jLabel11)
                        .addGap(73, 73, 73)
                        .addComponent(jLabel12))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(47, 47, 47)
                                .addComponent(jLabel7))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(356, 356, 356)
                                .addComponent(jLabel13)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(50, 50, 50)
                        .addComponent(jLabel5)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel3)
                        .addGap(55, 55, 55)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton8)
                            .addComponent(jLabel8))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(52, 52, 52)
                        .addComponent(jLabel2)
                        .addGap(289, 289, 289)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(148, 148, 148)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addComponent(jButton10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtext_name, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(550, Short.MAX_VALUE)
                    .addComponent(jLabel14)
                    .addGap(222, 222, 222)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(191, 191, 191)
                    .addComponent(jLabel15)
                    .addContainerGap(588, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton8)
                                .addGap(36, 36, 36)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(jLabel8)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jButton10)
                        .addGap(26, 26, 26)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtext_name, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel2)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(37, 37, 37)
                    .addComponent(jLabel14)
                    .addContainerGap(546, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(45, 45, 45)
                    .addComponent(jLabel15)
                    .addContainerGap(538, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    DefaultListModel dm =new DefaultListModel();
        DefaultListModel dm2 =new DefaultListModel();
DefaultListModel dm3 =new DefaultListModel();
    public void searchincustomer(){
        dm2.clear();
        try {
                    OracleDataSource ods;
            ods = new OracleDataSource();
            ods.setURL("jdbc:oracle:thin:@localhost:1521:orcl");
            ods.setUser("myproject");
            ods.setPassword("123456");
            Connection con = ods.getConnection();
            Statement st =con.createStatement();
            String acc ="select * from customer WHERE(customer.name = '"+jtext_name.getText()+"')";
             ResultSet rsacc= st.executeQuery(acc);
             Customer cu;
              EntityManagerFactory emf = Persistence.createEntityManagerFactory("bd_projectPU");
        EntityManager em =emf.createEntityManager();
            while(rsacc.next()){
            cu=em.find(Customer.class, rsacc.getLong("CUS_ID"));
             dm2.addElement(cu.toString());
            }
            jListcustomer.setModel(dm2);
           
        } catch (SQLException ex) {
            Logger.getLogger(accountat2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
     public void searchinproduct(){
        dm.clear();
        try {
                    OracleDataSource ods;
            ods = new OracleDataSource();
            ods.setURL("jdbc:oracle:thin:@localhost:1521:orcl");
            ods.setUser("myproject");
            ods.setPassword("123456");
            Connection con = ods.getConnection();
            Statement st =con.createStatement();
            String acc ="select * from product ";
             ResultSet rsacc= st.executeQuery(acc);
             
              EntityManagerFactory emf = Persistence.createEntityManagerFactory("bd_projectPU");
        EntityManager em =emf.createEntityManager();
              Product pr;
            while(rsacc.next()){
           pr=em.find(Product.class,rsacc.getBigDecimal("PRO_ID"));
            if(rsacc.getString("NAME").contains(jtext_name.getText()))
             dm.addElement(pr.toString());
            }
            jListproduct.setModel(dm);
           
        } catch (SQLException ex) {
            Logger.getLogger(accountat2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
     public void findallcustomer(){
         
         dm2.clear();
        try {
                    OracleDataSource ods;
            ods = new OracleDataSource();
            ods.setURL("jdbc:oracle:thin:@localhost:1521:orcl");
            ods.setUser("myproject");
            ods.setPassword("123456");
            Connection con = ods.getConnection();
            Statement st =con.createStatement();
            String acc ="select * from customer ";
             ResultSet rsacc= st.executeQuery(acc);
             Customer cu;
              EntityManagerFactory emf = Persistence.createEntityManagerFactory("bd_projectPU");       
              EntityManager em =emf.createEntityManager();
            while(rsacc.next()){
           cu=em.find(Customer.class, rsacc.getLong("CUS_ID"));
             dm2.addElement(cu.toString());
            }
            jListcustomer.setModel(dm2);
           
        } catch (SQLException ex) {
            Logger.getLogger(accountat2.class.getName()).log(Level.SEVERE, null, ex);
        }
     }
     public void findallproduct(){
          dm.clear();
        try {
                    OracleDataSource ods;
            ods = new OracleDataSource();
            ods.setURL("jdbc:oracle:thin:@localhost:1521:orcl");
            ods.setUser("myproject");
            ods.setPassword("123456");
            Connection con = ods.getConnection();
            Statement st =con.createStatement();
            String acc ="select * from product";
             ResultSet rsacc= st.executeQuery(acc);
           
              EntityManagerFactory emf = Persistence.createEntityManagerFactory("bd_projectPU");
        EntityManager em =emf.createEntityManager();
          Product pr;
            while(rsacc.next()){
           pr=em.find(Product.class,rsacc.getBigDecimal("PRO_ID"));
             dm.addElement(pr.toString());
            }
            jListproduct.setModel(dm);
           
        } catch (SQLException ex) {
            Logger.getLogger(accountat2.class.getName()).log(Level.SEVERE, null, ex);
        }
     }
      public void findallsalesman(){
          dm3.clear();
        try {
            
                    OracleDataSource ods;
            ods = new OracleDataSource();
            ods.setURL("jdbc:oracle:thin:@localhost:1521:orcl");
            ods.setUser("myproject");
            ods.setPassword("123456");
            Connection con = ods.getConnection();
            Statement st =con.createStatement();
            String acc ="select * from Salesman WHERE(Salesman.MANEGER_ID = '"+aa.getAccId()+"')";
             ResultSet rsacc= st.executeQuery(acc);
           
              EntityManagerFactory emf = Persistence.createEntityManagerFactory("bd_projectPU");
        EntityManager em =emf.createEntityManager();
          Salesman pr;
            while(rsacc.next()){
           pr=em.find(Salesman.class,rsacc.getLong("SM_ID"));
             dm3.addElement(pr.toString());
            }
            jListsalesman.setModel(dm3);
           
        } catch (SQLException ex) {
            Logger.getLogger(accountat2.class.getName()).log(Level.SEVERE, null, ex);
        }
     }
       public void searchsalesman(){
          dm3.clear();
        try {
            
                    OracleDataSource ods;
            ods = new OracleDataSource();
            ods.setURL("jdbc:oracle:thin:@localhost:1521:orcl");
            ods.setUser("myproject");
            ods.setPassword("123456");
            Connection con = ods.getConnection();
            Statement st =con.createStatement();
            String acc ="select * from Salesman WHERE(Salesman.name = '"+jtext_name.getText()+"')";
             ResultSet rsacc= st.executeQuery(acc);
           
              EntityManagerFactory emf = Persistence.createEntityManagerFactory("bd_projectPU");
        EntityManager em =emf.createEntityManager();
          Salesman pr;
            while(rsacc.next()){
           pr=em.find(Salesman.class,rsacc.getLong("SM_ID"));
             dm3.addElement(pr.toString());
            }
            jListsalesman.setModel(dm3);
           
        } catch (SQLException ex) {
            Logger.getLogger(accountat2.class.getName()).log(Level.SEVERE, null, ex);
        }
     }
//       public void edit(Object a){
//             
//        EntityManagerFactory emf = Persistence.createEntityManagerFactory("bd_projectPU");
//        EntityManager em =emf.createEntityManager();
//    if (a.equals(Salesman.class)){
//        
//        Salesman ss =(Salesman) a;
//         ss =em.find(Salesman.class, ss.getSmId());
//         
//         
//         
//                }else if(a.equals(Salesman.class)){
//                    
//                    
//                    
//                }else if(a.equals(Salesman.class)){
//                    
//                    
//                    
//                }
//       }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
salesmanframe_in_accountat bb =new salesmanframe_in_accountat();
bb.setuser2(aa);
bb.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if(jComboBox1.getSelectedIndex()==0)
       findallcustomer();
        if(jComboBox1.getSelectedIndex()==1)
        findallproduct();
          if(jComboBox1.getSelectedIndex()==2)
              findallsalesman();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed


 if(jComboBox1.getSelectedIndex()==0)
      searchincustomer();
        if(jComboBox1.getSelectedIndex()==1)
       searchinproduct();
        if(jComboBox1.getSelectedIndex()==2)
       searchsalesman();
        

//jList1.add()        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jtext_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtext_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtext_nameActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed

        accframe gg  =new accframe();
        gg.setuser(aa);
        gg.setVisible(true);
        
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        
          EntityManagerFactory emf = Persistence.createEntityManagerFactory("bd_projectPU");
        EntityManager em =emf.createEntityManager();
em.getTransaction().begin();
       
      
        if(!jListsalesman.isSelectionEmpty()) {
               String[] splited3 =  jListsalesman.getSelectedValue().split("     ");
      
             Salesman b=em.find(Salesman.class, Long.valueOf(splited3[0]));
           em.remove(b);
     em.getTransaction().commit();
       findallsalesman();
        }if(!jListcustomer.isSelectionEmpty()){
             String[] splited =  jListcustomer.getSelectedValue().split("     ");
                Customer b=em.find(Customer.class, Long.valueOf(splited[0]));
           em.remove(b);
        em.getTransaction().commit();
               findallcustomer();
        }
        if(!jListproduct.isSelectionEmpty()){
               String[] splited2 =  jListproduct.getSelectedValue().split("     ");
                   Product a=em.find(Product.class,BigDecimal.valueOf(Long.valueOf(splited2[0])));
             em.remove(a);
         em.getTransaction().commit();
               findallproduct();
        }if(jListcustomer.isSelectionEmpty()||jListproduct.isSelectionEmpty()||jListsalesman.isSelectionEmpty()) {
            JOptionPane.showMessageDialog(null, " select itme ");
    }
        em.getTransaction().commit();
       em.close();
     
       
    
      
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
              try
        {
            OracleDataSource ods = new OracleDataSource();
            ods.setURL("jdbc:oracle:thin:@localhost:1521:orcl");
            ods.setUser("myproject");
            ods.setPassword("123456");
       if(jComboBox1.getSelectedIndex()==0)
           {
              InputStream is = new FileInputStream(new File("allcustomer.jrxml"));
            JasperDesign jd = JRXmlLoader.load(is);
            JasperReport jr = JasperCompileManager.compileReport(jd);
            Connection conn = ods.getConnection();
            JasperPrint jp = JasperFillManager.fillReport(jr, null, conn);
            JFrame  frame =new JFrame("report");
            frame.getContentPane().add(new JRViewer(jp));
            frame.pack();
            frame.setVisible(true);
           is.close();
            conn.close();
            JOptionPane.showMessageDialog(null, "Done");
          }   
        if(jComboBox1.getSelectedIndex()==1)
        {
      
            InputStream is = new FileInputStream(new File("qasrawi.jrxml"));
            JasperDesign jd = JRXmlLoader.load(is);
            JasperReport jr = JasperCompileManager.compileReport(jd);
            Connection conn = ods.getConnection();
            JasperPrint jp = JasperFillManager.fillReport(jr, null, conn);
            JFrame  frame =new JFrame("report");
            frame.getContentPane().add(new JRViewer(jp));
            frame.pack();
            frame.setVisible(true);
           is.close();
            conn.close();
            JOptionPane.showMessageDialog(null, "Done");
        }
          if(jComboBox1.getSelectedIndex()==2)
          {
             HashMap parameter = new HashMap<String, Integer>();
            InputStream is = new FileInputStream(new File("allsalesman.jrxml"));
            JasperDesign jd = JRXmlLoader.load(is);
            JasperReport jr = JasperCompileManager.compileReport(jd);
            Connection conn = ods.getConnection();
              System.out.println((aa.getAccId()));
            parameter.put("man_id", (aa.getAccId()));
            JasperPrint jp = JasperFillManager.fillReport(jr, parameter, conn);
            JFrame  frame =new JFrame("report");
            frame.getContentPane().add(new JRViewer(jp));
            frame.pack();
            frame.setVisible(true);
          
            is.close();
            conn.close();
            JOptionPane.showMessageDialog(null, "Done");
          }         
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex.toString());
        }  
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

      
    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
 EntityManagerFactory emf = Persistence.createEntityManagerFactory("bd_projectPU");
        EntityManager em =emf.createEntityManager();
        em.getTransaction().begin();

        if(!jListcustomer.isSelectionEmpty()){
            String[] splited =  jListcustomer.getSelectedValue().split(" ");
            Customer b=em.find(Customer.class, Long.valueOf(splited[0]));
            create_customer  cc =new create_customer();
            cc.setsalesmanid(b.getSalesManId().getSmId());
            cc.edit_customer(b);
            cc.setVisible(true);
            em.getTransaction().commit();
            em.close();
            findallcustomer();
        }
        if(!jListproduct.isSelectionEmpty()){
            String[] splited2 =  jListproduct.getSelectedValue().split(" ");
            Product a=em.find(Product.class,BigDecimal.valueOf(Long.valueOf(splited2[0])));
            create_product aa=   new create_product();
            aa.edit_product(a);
            aa.setVisible(true);
            em.getTransaction().commit();
            em.close();
            findallproduct();
        }      
        if(!jListsalesman.isSelectionEmpty()){
            String[] splited2 =  jListsalesman.getSelectedValue().split(" ");
            Salesman a=em.find(Salesman.class,Long.valueOf(splited2[0]));
            salesmanframe ss=new salesmanframe();
        ss.setVisible(true);
        ss.setuser(a);
            em.getTransaction().commit();
            em.close();
            findallproduct();
        }     
        
        
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jListsalesmanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListsalesmanMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jListsalesmanMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
     this.dispose();
     new login().setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(accountat2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(accountat2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(accountat2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(accountat2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new accountat2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jListcustomer;
    private javax.swing.JList<String> jListproduct;
    private javax.swing.JList<String> jListsalesman;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jtext_name;
    // End of variables declaration//GEN-END:variables
}
