/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bd_project;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;
import oracle.jdbc.pool.OracleDataSource;

/**
 *
 * @author data base
 */
public class creat_new_account extends javax.swing.JFrame {

    /**
     * Creates new form sel_frame
     */
    public creat_new_account() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jText_phone = new javax.swing.JTextField();
        jText_salary = new javax.swing.JTextField();
        jtname = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jText_address = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();
        jmanger_id = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText(" Person Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 40, -1, -1));

        jLabel3.setText("Phone");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, -1, -1));

        jLabel5.setText("Salary");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, -1, -1));
        getContentPane().add(jText_phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, 130, -1));
        getContentPane().add(jText_salary, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, 130, -1));

        jtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtnameActionPerformed(evt);
            }
        });
        getContentPane().add(jtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 40, 190, -1));
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 180, 130, -1));

        jLabel7.setText("Address");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, -1, -1));

        jLabel8.setText("Birthday");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 180, -1, -1));
        getContentPane().add(jText_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, 130, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bd_project/portrait-salesman .jpg"))); // NOI18N
        jButton1.setText("Save as salesman");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 120, 220, 180));

        jLabel4.setText("password");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 90, -1, -1));
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 80, 130, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bd_project/accountat_photo.jpg"))); // NOI18N
        jButton2.setText("Save as accountat");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 190));

        jmanger_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmanger_idActionPerformed(evt);
            }
        });
        getContentPane().add(jmanger_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 130, 130, -1));

        jLabel6.setText("manger ID");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 130, -1, -1));

        jLabel1.setText("Save  as Accountat");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 130, 30));

        jLabel9.setText("Save  as Salesman");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 80, 130, 30));

        jButton3.setText("return");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtnameActionPerformed


    }//GEN-LAST:event_jtnameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try{
       
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("bd_projectPU");
        EntityManager em =emf.createEntityManager();
        Salesman aa=new Salesman();
      // aa.setSmId(Long.parseLong(jtext_id.getText()));
      long m_id;
      m_id=Long.parseLong(jmanger_id.getText());
      
      aa.setManegerId(em.find(Accountat.class,m_id));
              
              
              
     // aa.setManegerId();
       aa.setName(jtname.getText());
       aa.setAdress(jText_address.getText());
       aa.setPassword(String.valueOf(jPasswordField1.getPassword()));
       aa.setPhone(Long.parseLong(jText_phone.getText()));
       aa.setSalary((int) Long.parseLong(jText_salary.getText()));
           Date date1=new SimpleDateFormat("dd/MM/yyyy").parse(jTextField7.getText());  

       aa.setBirthday(date1);
       em.getTransaction().begin();
       em.persist(aa);
       em.getTransaction().commit();
       em.close();
       jtname.setText("");
       jText_address.setText("");
       jPasswordField1.setText("");
       jText_phone.setText("");
       jText_salary.setText("");
       jTextField7.setText("");
  
         JOptionPane.showMessageDialog(null," your ID is : \n"+aa.getSmId());
               }catch(Exception ex) {
            JOptionPane.showMessageDialog(null, ex.toString());
        }

 



    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         try{
       
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("bd_projectPU");
        EntityManager em =emf.createEntityManager();
        Accountat aa=new Accountat();
    //   aa.setAccId(Long.parseLong(jtext_id.getText()));
       aa.setName(jtname.getText());
       aa.setAdress(jText_address.getText());
       aa.setPassword(String.valueOf(jPasswordField1.getPassword()));
       aa.setPhone(Long.parseLong(jText_phone.getText()));
       aa.setSalary((int) Long.parseLong(jText_salary.getText()));
           Date date1=new SimpleDateFormat("dd/MM/yyyy").parse(jTextField7.getText());  

       aa.setBirthday(date1);
       em.getTransaction().begin();
       em.persist(aa);
       em.getTransaction().commit();
       em.close();
       jtname.setText("");
       jText_address.setText("");
       jPasswordField1.setText("");
       jText_phone.setText("");
       jText_salary.setText("");
       jTextField7.setText("");
  
           JOptionPane.showMessageDialog(null," your ID is : \n"+aa.getAccId());
       
               }catch(Exception ex) {
            JOptionPane.showMessageDialog(null, ex.toString());
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jmanger_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmanger_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmanger_idActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    new manger().setVisible(true);
     this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(creat_new_account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(creat_new_account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(creat_new_account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(creat_new_account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new creat_new_account().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jText_address;
    private javax.swing.JTextField jText_phone;
    private javax.swing.JTextField jText_salary;
    private javax.swing.JTextField jmanger_id;
    private javax.swing.JTextField jtname;
    // End of variables declaration//GEN-END:variables
}
