/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bd_project;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import oracle.jdbc.pool.OracleDataSource;

/**
 *
 * @author data base
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextid = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("creat new person");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 160, 30));

        jButton2.setText("login");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 180, 160, 40));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Person ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 90, 20));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Password");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 90, -1));

        jTextid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextidActionPerformed(evt);
            }
        });
        getContentPane().add(jTextid, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, 190, -1));

        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, 190, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bd_project/business (Copy).jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 250));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextidActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        new manger().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        OracleDataSource ods;
        try {
            ods = new OracleDataSource();
            ods.setURL("jdbc:oracle:thin:@localhost:1521:orcl");
            ods.setUser("myproject");
            ods.setPassword("123456");
            Connection con = ods.getConnection();
            Statement st =con.createStatement();
            Statement st1 =con.createStatement();

            String acc ="select * from accountat";
            String sal ="select * from salesman";
             //String man ="select salesman.password,sm_id from salesman";
            ResultSet rsacc= st1.executeQuery(acc);
            ResultSet rssal= st.executeQuery(sal);
          //  ResultSet rsman= st.executeQuery(man);
                        Accountat ac=new Accountat();
                        Salesman sa= new Salesman();
     while(rsacc.next()){
               
               String pass =rsacc.getString("password");
               String id =rsacc.getString("acc_id");  
                 ac.setAccId(rsacc.getLong("acc_id"));
                    ac.setName(rsacc.getString("NAME"));
                   ac.setPhone(rsacc.getLong("PHONE"));
                   ac.setAdress(rsacc.getString("ADRESS"));
                   ac.setBirthday(rsacc.getDate("BIRTHDAY"));
                   ac.setSalary(rsacc.getInt("SALARY"));
                   ac.setPassword(rsacc.getString("password"));
               if(pass.equals(jPasswordField1.getText())&&id.equals(jTextid.getText())){
                   accountat2 bb =new accountat2();
                   bb.setVisible(true);
                   bb.setuser(ac);
                     this.setVisible(false);
//                      accframe fr=  new accframe();    
//                        fr.setVisible(true);
//                        fr.setuser(ac);
//                        this.setVisible(false);
                       return;
                       // 
                    }
              
            }
            
                    while(rssal.next()){
               
               String pass =rssal.getString("password");
               String id =rssal.getString("sm_id");
               sa.setSmId(rssal.getLong("sm_id"));
                    sa.setName(rssal.getString("NAME"));
                  sa.setPhone(rssal.getLong("PHONE"));
                   sa.setAdress(rssal.getString("ADRESS"));
                   sa.setBirthday(rssal.getDate("BIRTHDAY"));
                   sa.setSalary(rssal.getInt("SALARY"));
                   sa.setPassword(rssal.getString("password"));
                      
               if(pass.equals(jPasswordField1.getText())&&id.equals(jTextid.getText())){
                 
//                      salesmanframe  fr=  new salesmanframe();
//                      fr.setVisible(true);    
//                      fr.setuser(sa);
                      sealman2 salesframe =new sealman2();
                      salesframe.setVisible(true);
                      salesframe.setuser(sa);
                      this.setVisible(false);
                        return;
                  
                  
               }
               
            }
                     JOptionPane.showMessageDialog(null,"uncorect password or id " ,"error" , 1);
       
        
            
          } catch (Exception ex) {
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextid;
    // End of variables declaration//GEN-END:variables
}
