/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bd_project;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;

/**
 *
 * @author data base
 */
public class salesmanframe_in_accountat extends javax.swing.JFrame {

    
    Salesman aa;
    Accountat bb;
    /**
     * Creates new form sel_frame
     */
    public salesmanframe_in_accountat() {
        initComponents();
    }

    public void setuser2(Accountat a){
        bb=a;
      


    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jText_phone = new javax.swing.JTextField();
        jText_salary = new javax.swing.JTextField();
        jtname = new javax.swing.JTextField();
        jbirth_day = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jText_address = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText(" Person Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 93, 98, -1));

        jLabel3.setText("Phone");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, -1, -1));

        jLabel5.setText("Salary");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 145, -1, -1));
        getContentPane().add(jText_phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, 185, -1));
        getContentPane().add(jText_salary, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 142, 170, -1));

        jtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtnameActionPerformed(evt);
            }
        });
        getContentPane().add(jtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 90, 170, -1));
        getContentPane().add(jbirth_day, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, 185, -1));

        jLabel7.setText("Address");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 188, -1, -1));

        jLabel8.setText("Birthday");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, -1, -1));
        getContentPane().add(jText_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 185, 170, -1));

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 210, 89, -1));

        jLabel4.setText("password");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, -1, -1));
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, 185, -1));

        jLabel6.setText("sales man information");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 0, 133, 26));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bd_project/portrait-salesman .jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 30, 310, 240));

        jButton2.setText("close");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtnameActionPerformed


    }//GEN-LAST:event_jtnameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try{
       
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("bd_projectPU");
        EntityManager em =emf.createEntityManager();
      aa= new Salesman();
       aa.setName(jtname.getText());
       aa.setAdress(jText_address.getText());
       aa.setPassword(String.valueOf(jPasswordField1.getPassword()));
       aa.setPhone(Long.parseLong(jText_phone.getText()));
       aa.setSalary((int) Long.parseLong(jText_salary.getText()));
       Date date1=new SimpleDateFormat("dd/MM/yyyy").parse(jbirth_day.getText());  
       aa.setManegerId(bb);
       aa.setBirthday(date1);
       em.getTransaction().begin();
       em.persist(aa);
       em.getTransaction().commit();
       em.close();
  
       
               }catch(Exception ex) {
            JOptionPane.showMessageDialog(null, ex.toString());
        }

       this.dispose();
    



    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(salesmanframe_in_accountat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(salesmanframe_in_accountat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(salesmanframe_in_accountat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(salesmanframe_in_accountat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new salesmanframe_in_accountat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jText_address;
    private javax.swing.JTextField jText_phone;
    private javax.swing.JTextField jText_salary;
    private javax.swing.JTextField jbirth_day;
    private javax.swing.JTextField jtname;
    // End of variables declaration//GEN-END:variables
}
