/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bd_project;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.io.OutputStream;
import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.xml.bind.annotation.XmlElement;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.swing.JRViewer;
import oracle.jdbc.pool.OracleDataSource;

/**
 *
 * @author data base
 */
public class sealman2 extends javax.swing.JFrame {

    /**
     * Creates new form sealman2
     */
    public sealman2() {
        initComponents();
         jPanel1.addMouseListener(new MouseAdapter() {
                public void mousePressed(MouseEvent e) {
                   jListcustomer.clearSelection();
                   jListproduct.clearSelection();
                
                  
                }           
            });
    }
     Salesman aa;
   
   public void setuser(Salesman a){
       aa=a;
               System.out.println("                                 \n"+aa.getSmId() );

       
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListproduct = new javax.swing.JList<>();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListcustomer = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtext_name = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(255, 61, 6));

        jPanel1.setBackground(new java.awt.Color(0, 204, 255));

        jButton6.setText("all cusomer");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton5.setText("all product");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton10.setText("product for selected customer");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jLabel9.setText("Genareat Report");

        jButton4.setText("add new product");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel5.setText("name");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "customer", "product" }));

        jLabel6.setText("price");

        jButton7.setText("delete");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel7.setText("availability");

        jListproduct.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(jListproduct);

        jLabel8.setText("place");

        jButton1.setText("search in ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton8.setText("Edit my Information");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton2.setText("add new customer");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton9.setText("<< Add");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton3.setText("show all ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jListcustomer.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jListcustomer);

        jLabel2.setText("name");

        jLabel3.setText("store type");

        jtext_name.setText("name");
        jtext_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtext_nameActionPerformed(evt);
            }
        });

        jLabel4.setText("ID");

        jLabel1.setText("ID");

        jButton11.setText("Edit");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setText("Log Out");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton9))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jLabel9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(50, 50, 50)
                        .addComponent(jLabel5)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel6)
                        .addGap(75, 75, 75)
                        .addComponent(jLabel7))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton8)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jtext_name, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(32, 32, 32)
                                .addComponent(jLabel2)
                                .addGap(37, 37, 37)
                                .addComponent(jLabel3))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(jLabel8))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton12)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton2)
                    .addComponent(jButton8))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jButton9))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addComponent(jLabel8))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7)))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addComponent(jtext_name, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jButton11))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed

        EntityManagerFactory emf = Persistence.createEntityManagerFactory("bd_projectPU");
        EntityManager em =emf.createEntityManager();
        em.getTransaction().begin();

        if(!jListcustomer.isSelectionEmpty()){
            String[] splited =  jListcustomer.getSelectedValue().split(" ");
            Customer b=em.find(Customer.class, Long.valueOf(splited[0]));
            create_customer  cc =new create_customer();
            cc.setsalesmanid(aa.getSmId());
            cc.edit_customer(b);
            cc.setVisible(true);
            em.getTransaction().commit();
            em.close();
            findallcustomer();
        }
        if(!jListproduct.isSelectionEmpty()){
            String[] splited2 =  jListproduct.getSelectedValue().split(" ");
            Product a=em.find(Product.class,BigDecimal.valueOf(Long.valueOf(splited2[0])));
            create_product aa=   new create_product();
            aa.edit_product(a);
            aa.setVisible(true);
            em.getTransaction().commit();
            em.close();
            findallproduct();
        }

    }//GEN-LAST:event_jButton11ActionPerformed

    private void jtext_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtext_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtext_nameActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if(jComboBox1.getSelectedIndex()==0)
        findallcustomer();
        if(jComboBox1.getSelectedIndex()==1)
        findallproduct();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed

        try{
            EntityManagerFactory emf = Persistence.createEntityManagerFactory("bd_projectPU");
            EntityManager em =emf.createEntityManager();
            em.getTransaction().begin();

            if(!jListcustomer.isSelectionEmpty()&&!jListproduct.isSelectionEmpty()) {
                String[] splited =  jListcustomer.getSelectedValue().split("     ");
                String[] splited2 =  jListproduct.getSelectedValue().split("     ");
                Product a=em.find(Product.class,BigDecimal.valueOf(Long.valueOf(splited2[0])));
                Customer b=em.find(Customer.class, Long.valueOf(splited[0]));

                if(a.getAvailable()==1){
                    em.createNativeQuery("INSERT into buy(customer_id,PRODUCT_ID) VALUES (?,?)")
                    .setParameter(1, b.getCusId())
                    .setParameter(2, a.getProId())
                    .executeUpdate();
                }
                else
                JOptionPane.showMessageDialog(null, "this product in unavlible");
                em.getTransaction().commit();
                em.close();
            }else {
                JOptionPane.showMessageDialog(null, " select itme ");
            }
        }catch(Exception ex) {
            JOptionPane.showMessageDialog(null, "  this oprator is allready done ");
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        create_customer cu=new create_customer();
        cu.setVisible(true);
        cu.setsalesmanid(aa.getSmId());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        salesmanframe ss=new salesmanframe();
        ss.setVisible(true);
        ss.setuser(aa);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if(jComboBox1.getSelectedIndex()==0)
        searchincustomer();
        if(jComboBox1.getSelectedIndex()==1)
        searchinproduct();

        //jList1.add()        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed

        EntityManagerFactory emf = Persistence.createEntityManagerFactory("bd_projectPU");
        EntityManager em =emf.createEntityManager();
        em.getTransaction().begin();

        if(!jListcustomer.isSelectionEmpty()&&!jListproduct.isSelectionEmpty()) {
            String[] splited =  jListcustomer.getSelectedValue().split(" ");
            String[] splited2 =  jListproduct.getSelectedValue().split(" ");
            Product a=em.find(Product.class,BigDecimal.valueOf(Long.valueOf(splited2[0])));
            em.remove( a);
            Customer b=em.find(Customer.class, Long.valueOf(splited[0]));
            em.remove(b);
            em.getTransaction().commit();
            em.close();
            findallcustomer();
            findallproduct();
        } else if(!jListcustomer.isSelectionEmpty()){
            String[] splited =  jListcustomer.getSelectedValue().split("      ");
            Customer b=em.find(Customer.class, Long.valueOf(splited[0]));
            em.remove(b);
            em.getTransaction().commit();
            em.close();
            findallcustomer();
        }else if(!jListproduct.isSelectionEmpty()){
            String[] splited2 =  jListproduct.getSelectedValue().split("      ");
            Product a=em.find(Product.class,BigDecimal.valueOf(Long.valueOf(splited2[0])));
            em.remove(a);
            em.getTransaction().commit();
            em.close();
            findallproduct();
        }else {
            JOptionPane.showMessageDialog(null, " select itme ");
        }

    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        new create_product().setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed

        try
        {
            if(!jListcustomer.isSelectionEmpty()){
                OracleDataSource ods = new OracleDataSource();
                ods.setURL("jdbc:oracle:thin:@localhost:1521:orcl");
                ods.setUser("myproject");
                ods.setPassword("123456");
                HashMap parameter = new HashMap<String, Integer>();
                InputStream is = new FileInputStream(new File("buy.jrxml"));
                JasperDesign jd = JRXmlLoader.load(is);
                JasperReport jr = JasperCompileManager.compileReport(jd);
                Connection conn = ods.getConnection();
                Customer b=null;

                EntityManagerFactory emf = Persistence.createEntityManagerFactory("bd_projectPU");
                EntityManager em =emf.createEntityManager();
                em.getTransaction().begin();
                String[] splited =  jListcustomer.getSelectedValue().split("     ");
                b=em.find(Customer.class, Long.valueOf(splited[0]));

                parameter.put("cus_id", (b.getCusId()));
                parameter.put("cus_name", (b.getName()));
                parameter.put("cus_add", (b.getAddress()));
                JasperPrint jp = JasperFillManager.fillReport(jr, parameter, conn);
                JFrame  frame =new JFrame("report");
                frame.getContentPane().add(new JRViewer(jp));
                frame.pack();
                frame.setVisible(true);
                //            OutputStream os = new FileOutputStream(new File("Hw_Report_By_obada.pdf"));
                //            JasperExportManager.exportReportToPdfStream(jp, os);
                //            os.close();
                //            is.close();
                conn.close();
                JOptionPane.showMessageDialog(null, "Done");
            }
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex.toString());
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try
        {
            OracleDataSource ods = new OracleDataSource();
            ods.setURL("jdbc:oracle:thin:@localhost:1521:orcl");
            ods.setUser("myproject");
            ods.setPassword("123456");
            //   HashMap parameter = new HashMap<String, Integer>();
            InputStream is = new FileInputStream(new File("qasrawi.jrxml"));
            JasperDesign jd = JRXmlLoader.load(is);
            JasperReport jr = JasperCompileManager.compileReport(jd);
            Connection conn = ods.getConnection();
            // parameter.put("sealesman_id", (aa.getSmId()));
            JasperPrint jp = JasperFillManager.fillReport(jr, null, conn);

            JFrame  frame =new JFrame("report");
            frame.getContentPane().add(new JRViewer(jp));
            frame.pack();
            frame.setVisible(true);
            // OutputStream os = new FileOutputStream(new File("Hw_Report_By_obada.pdf"));
            //  JasperExportManager.exportReportToPdfStream(jp, os);
            //   os.close();
            is.close();
            conn.close();
            JOptionPane.showMessageDialog(null, "Done");

        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex.toString());
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

        try
        {
            OracleDataSource ods = new OracleDataSource();
            ods.setURL("jdbc:oracle:thin:@localhost:1521:orcl");
            ods.setUser("myproject");
            ods.setPassword("123456");
            HashMap parameter = new HashMap<String, Integer>();
            InputStream is = new FileInputStream(new File("customer.jrxml"));
            JasperDesign jd = JRXmlLoader.load(is);
            JasperReport jr = JasperCompileManager.compileReport(jd);
            Connection conn = ods.getConnection();
            parameter.put("sealesman_id", (aa.getSmId()));
            JasperPrint jp = JasperFillManager.fillReport(jr, parameter, conn);

            JFrame  frame =new JFrame("report");
            frame.getContentPane().add(new JRViewer(jp));
            frame.pack();
            frame.setVisible(true);
            // OutputStream os = new FileOutputStream(new File("Hw_Report_By_obada.pdf"));
            //  JasperExportManager.exportReportToPdfStream(jp, os);
            //   os.close();
            is.close();
            conn.close();
            JOptionPane.showMessageDialog(null, "Done");

        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex.toString());
        }

    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
     this.dispose();
     new login().setVisible(true);
    }//GEN-LAST:event_jButton12ActionPerformed

    DefaultListModel dm =new DefaultListModel();
        DefaultListModel dm2 =new DefaultListModel();

    public void searchincustomer(){
        dm2.clear();
        try {
                    OracleDataSource ods;
            ods = new OracleDataSource();
            ods.setURL("jdbc:oracle:thin:@localhost:1521:orcl");
            ods.setUser("myproject");
            ods.setPassword("123456");
            Connection con = ods.getConnection();
            Statement st =con.createStatement();
//            and(customer.name = '"+jtext_name.getText()+"')
            String acc ="select * from customer WHERE( sales_man_id="+aa.getSmId()+")";
             ResultSet rsacc= st.executeQuery(acc);
             Customer cu;
              EntityManagerFactory emf = Persistence.createEntityManagerFactory("bd_projectPU");
        EntityManager em =emf.createEntityManager();
            while(rsacc.next()){
            cu=em.find(Customer.class, rsacc.getLong("CUS_ID"));
            if(cu.toString().contains(jtext_name.getText()))
             dm2.addElement(cu.toString());
            }
            jListcustomer.setModel(dm2);
           
        } catch (SQLException ex) {
            Logger.getLogger(sealman2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
     public void searchinproduct(){
        dm.clear();
        try {
                    OracleDataSource ods;
            ods = new OracleDataSource();
            ods.setURL("jdbc:oracle:thin:@localhost:1521:orcl");
            ods.setUser("myproject");
            ods.setPassword("123456");
            Connection con = ods.getConnection();
            Statement st =con.createStatement();
            String acc ="select * from product ";
             ResultSet rsacc= st.executeQuery(acc);
             
              EntityManagerFactory emf = Persistence.createEntityManagerFactory("bd_projectPU");
        EntityManager em =emf.createEntityManager();
              Product pr;
            while(rsacc.next()){
           pr=em.find(Product.class,rsacc.getBigDecimal("PRO_ID"));
            if(rsacc.getString("NAME").contains(jtext_name.getText()))
             dm.addElement(pr.toString());
            }
            jListproduct.setModel(dm);
           
        } catch (SQLException ex) {
            Logger.getLogger(sealman2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
     public void findallcustomer(){
         
         dm2.clear();
        try {
                    OracleDataSource ods;
            ods = new OracleDataSource();
            ods.setURL("jdbc:oracle:thin:@localhost:1521:orcl");
            ods.setUser("myproject");
            ods.setPassword("123456");
            Connection con = ods.getConnection();
            Statement st =con.createStatement();
            String acc ="select * from customer WHERE( sales_man_id="+aa.getSmId()+")";
             ResultSet rsacc= st.executeQuery(acc);
             Customer cu;
              EntityManagerFactory emf = Persistence.createEntityManagerFactory("bd_projectPU");       
              EntityManager em =emf.createEntityManager();
            while(rsacc.next()){
           cu=em.find(Customer.class, rsacc.getLong("CUS_ID"));
             dm2.addElement(cu.toString());
            }
            jListcustomer.setModel(dm2);
           
        } catch (SQLException ex) {
            Logger.getLogger(sealman2.class.getName()).log(Level.SEVERE, null, ex);
        }
     }
     public void findallproduct(){
          dm.clear();
        try {
                    OracleDataSource ods;
            ods = new OracleDataSource();
            ods.setURL("jdbc:oracle:thin:@localhost:1521:orcl");
            ods.setUser("myproject");
            ods.setPassword("123456");
            Connection con = ods.getConnection();
            Statement st =con.createStatement();
            String acc ="select * from product";
             ResultSet rsacc= st.executeQuery(acc);
           
              EntityManagerFactory emf = Persistence.createEntityManagerFactory("bd_projectPU");
        EntityManager em =emf.createEntityManager();
          Product pr;
            while(rsacc.next()){
           pr=em.find(Product.class,rsacc.getBigDecimal("PRO_ID"));
             dm.addElement(pr.toString());
            }
            jListproduct.setModel(dm);
           
        } catch (SQLException ex) {
            Logger.getLogger(sealman2.class.getName()).log(Level.SEVERE, null, ex);
        }
     }
    private void jList3ValueChanged(javax.swing.event.ListSelectionEvent evt) {                                    

    
      jListcustomer.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
      jListcustomer.addListSelectionListener((ListSelectionEvent le) -> {
         Customer x= (Customer)((JList)le.getSource()).getSelectedValue();
         
      });



} 
//    cus_id
//            cus_name
//            cus_add
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sealman2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sealman2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sealman2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sealman2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sealman2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jListcustomer;
    private javax.swing.JList<String> jListproduct;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jtext_name;
    // End of variables declaration//GEN-END:variables
}
